### PR TITLE
[4] Angular migration.

### PR DESCRIPTION
**Pull request by AndreyKoltsov1997**
**Now**
We have front-end files based on vanilla JS and HTML files.

**Then**
We could be more flexible in out front-end development using frameworks like Angular - it'd allow us to use existing modules and structure the front-end logic.

Issue: https://github.com/katevi/Chat/issues/14

### CODE REVIEW

**Comment by AndreyKoltsov1997** [comment]
@katevi in order to review the changes easier, please, configure the file filters:
image

**Comment by katevi** [comment]
I've stucked with such problem: name of sender is always Andrey:)
Is it okay and we should add simple users later (in next PR)?
image

**Comment by AndreyKoltsov1997** [comment]
@katevi please, note that registration won't work until https://github.com/katevi/Chat/pull/25 would be merged.

**Comment by katevi** [comment]
All works for me, but there are some conflict files in this branch:)
Should I resolve conflicy by myself, or it would be better you to do this?

**Comment by AndreyKoltsov1997** [comment]
> All works for me, but there are some conflict files in this branch:)
> Should I resolve conflict by myself, or it would be better you to do this?

I'll resolve it.

**Pull request merged**
